android-study-independent/project_akhir_team3

.idea/gradle.xml, .idea/misc.xml, app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/finalproject_chilicare/data/api/HeaderInterceptor.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/Network.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/Retro.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/Routes.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/UserAPI.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/RegisterRequest.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/RegisterResponse.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/UserRequest.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/UserResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/LoginActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/RegisterActivity.kt, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_register.xml
mengerjakan bagian logic pada register supaya data bisa melakukan login terlebih dahulu pada postman /login
=> mengerjakan bagian logic pada register

app/src/main/java/com/example/finalproject_chilicare/data/response/LoginResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/HomeActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/LoginActivity.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_login.xml
1. penmabahan shared prefrences pada halaman login
2. membuat button logout juga sebagai action untuk keluar (bersifat sementara saja, nanti dipindahkan lagi)
=> penambahan shared prefrences di halaman login

app/src/main/java/com/example/finalproject_chilicare/ui/LoginActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/RegisterActivity.kt
update server ngrok terbaru, untuk testing debug tim (sementara)
=> update server ngrok sementara, untuk testing tim

app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_register.xml, app/src/main/res/values/colors.xml
Saya memperbaiki layout register dan login dan menambah warna di colors.xml
=> Revisi layout login dan register

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/finalproject_chilicare/ui/home/WeatherActivity.kt, app/src/main/res/layout/activity_weather.xml
menambahkan fitur ask permission for location di weather
=> add ask permission for location

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/finalproject_chilicare/ui/home/article/DetailArticleActivity.kt, app/src/main/res/drawable/bg_article.xml, app/src/main/res/drawable/bg_border_article.xml, app/src/main/res/drawable/border_article.xml, app/src/main/res/layout/activity_detail_article.xml
Saya sudah menyelesaikan layout DetailArticelnya namun dibagian DetailArticelActivity saya memiliki error masalah Referensi yang belum terselesaikan: argumen filteredList dan Type tidak berada dalam batasannya: harus berupa subtipe dari 'Parcelable!'. Referensi yang belum terselesaikan itu dari home.article.card.cardClass. Jika saya menambakan Parcelable di cardClass akan terjadi error di ArticelActivitynya.
=> Membuat layout dan logic DetailArticleActivity

app/src/main/java/com/example/finalproject_chilicare/ui/home/DetailArticleActivity.kt, app/src/main/res/layout/activity_detail_article.xml, app/src/main/res/values/strings.xml
1. Saya telah menambhakan logic untuk memanggil card artikel ke bawah bagian layout Detail Artikel
2. Saya mengubah layout Detail artikel rv_cardArticle menjadi rv_cardArticle2
3. Saya  menambahkan dibagian string <string-array, data artikel menjadi string.
=> Penambahan logic detail article lainnya dan penambahan card data ke String

app/src/main/res/layout/activity_weather.xml
membetulkan sedikit layout di weather
=> membetulkan sedikit layout di weather

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/finalproject_chilicare/adapter/CardAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/adapter/PopularCityAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/PopularCityResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/ArticleActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/DetailArticleActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/SearchPopularCityActivity.kt, app/src/main/java/com/example/finalproject_chilicare/utils/DummyDataArtikel.kt, app/src/main/res/layout/activity_detail_article.xml, app/src/main/res/layout/activity_search_popular_city.xml, app/src/main/res/layout/card_popular_city.xml, app/src/main/res/values/strings.xml
- memperbaiki review dari ka tama, untuk data dummy dari artikel dijadikan menjadi object
- memperbaiki halaman detail artikel pada recyclerview yang paling bawah sendiri
- memperbaiki navigate pada halaman artikel agar bisa berfungsi dengan baik
- membantu task dari mas haryadi yaitu membikin recyclerview dengan 4 data item secara horizontal
- halaman artikel sudah berfungsi dengan data dummy sementara (- yang belum mungkin filtering tab nya)"
=> Artikel resolve

app/src/main/java/com/example/finalproject_chilicare/adapter/HourlyWeatherAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/Hourlyweather.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/SearchPopularCityActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/WeatherActivity.kt, app/src/main/res/layout/activity_search_popular_city.xml, app/src/main/res/layout/activity_weather.xml, app/src/main/res/layout/card_hourly_weather.xml, app/src/main/res/values/strings.xml
Mengubah tampilan di weather activity pada bagian hourly weather dan melakukan resolved conflict
=> resolved weather

app/src/main/java/com/example/finalproject_chilicare/data/models/Forecast.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/WeatherActivity.kt, app/src/main/res/drawable/baseline_keyboard_arrow_down_24.xml, app/src/main/res/layout/activity_weather.xml
Membetulkan layouting pada bagian weather
=> resolved layouting weather

app/src/main/java/com/example/finalproject_chilicare/adapter/HourlyWeatherAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/Hourlyweather.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/WeatherActivity.kt, app/src/main/res/layout/card_hourly_weather.xml
Menyelesaikan pada bagian weather activity terutama untuk akses current location
=> Finish weather activity

app/src/main/java/com/example/finalproject_chilicare/adapter/ForumAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/adapter/forum/MainForumAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/Network.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/AllForumItem.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/AllForumResponse.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/NewGetForum.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/ForumActivity.kt, app/src/main/res/layout/activity_forum.xml
=> resolved pada forum

app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/AllForumItem.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/AllForumResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/ForumActivity.kt, app/src/main/res/layout/activity_forum.xml
mengambil data untuk recycler view pada forum
=> berhasil mengambil data menggunakan parameter di header

app/src/main/java/com/example/finalproject_chilicare/adapter/lms/CardLmsMateriAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/adapter/lms/CardLmsModulAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/adapter/lms/TabLmsAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/lms/ListMateriLMS.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/lms/ModulMateri.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/lms/ModulStatusRespn.kt, app/src/main/java/com/example/finalproject_chilicare/ui/lms/LmsFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/lms/MateriLMSActivity.kt, app/src/main/res/layout/activity_materi_lmsactivity.xml, app/src/main/res/layout/card_lms_module.xml, app/src/main/res/layout/fragment_lms.xml, app/src/main/res/layout/tab_lms.xml
- memperbaiki get API pada lms
- memperbaiki layouting pada card materi dan modul
=> resolve get API LMS

app/src/main/java/com/example/finalproject_chilicare/adapter/forum/MainForumAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/PreferencesHelper.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/EditForumResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/EditPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/ForumActivity.kt, app/src/main/res/layout/activity_edit_post_forum.xml
Berhasil memberikan fungsi untuk Delete dan Edit forum, namun masih belum sempurna
=> Delete and Edit logic done

app/src/main/java/com/example/finalproject_chilicare/adapter/lms/CardLmsMateriAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/PreferencesHelper.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/api/Network.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/DetailPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/EditPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/ForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/NewPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/lms/DetailLMSActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/lms/MateriLMSActivity.kt, app/src/main/res/layout/activity_materi_lmsactivity.xml, app/src/main/res/layout/card_lms_materi.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_lms.xml
- menambahkan code perbaikan fdi forum
=> perbaikan forum

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/finalproject_chilicare/ui/profile/ProfileFragment.kt, app/src/main/res/layout/card_lms_module.xml, app/src/main/res/layout/fragment_favorite.xml
…ut yang ada difavorite fargment dan card lms module
=> Membuat logout aplikasi kembali di LoginActivity dan membenarkan layout yang ada difavorite fragment dan card lms module

app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/DetailPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/EditPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/ForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/login/LoginActivity.kt, app/src/main/res/layout/activity_detail_post_forum.xml
Melakukan pengecekan ulang terhadap aplikasi
=> melakukan cek ulang aplikasi

app/src/main/java/com/example/finalproject_chilicare/adapter/PopularCityAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/HomeFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/SearchPopularCityActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/WeatherActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/article/ArticleActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/weather/WeatherJakartaActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/lms/LmsFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/profile/ProfileFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/splashscreen/SplashScreenActivity.kt, app/src/main/res/layout/activity_article.xml, app/src/main/res/layout/activity_splash_screen.xml, app/src/main/res/layout/activity_weather.xml, app/src/main/res/layout/activity_weather_jakarta.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_lms.xml, app/src/main/res/layout/fragment_profile.xml
- saya mempercantik dan merapihkan tampilan dengan menambahkan tampilan loading menggunakan progress bar disetiap masuk activity
=> menambahkan progressbar pada tampila awal layout dan activity

app/src/main/java/com/example/finalproject_chilicare/adapter/forum/KomentarAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/CommentRequest.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/IsiComentarItem.kt, app/src/main/java/com/example/finalproject_chilicare/data/models/PostKomentarDetailForumResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/DetailPostForumActivity.kt, app/src/main/res/layout/activity_detail_post_forum.xml, app/src/main/res/layout/activity_new_post_forum.xml, app/src/main/res/layout/card_comment.xml
=> memperbaiki apk

app/src/main/java/com/example/finalproject_chilicare/adapter/forum/KomentarAdapter.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/forum/ForumResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/EditPostForumActivity.kt
=> finishing APK

app/src/main/java/com/example/finalproject_chilicare/data/api/ApiInterface.kt, app/src/main/java/com/example/finalproject_chilicare/data/response/login/LoginResponse.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/HomeFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/home/forum/NewPostForumActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/login/LoginActivity.kt, app/src/main/java/com/example/finalproject_chilicare/ui/profile/ProfileFragment.kt, app/src/main/java/com/example/finalproject_chilicare/ui/register/RegisterActivity.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_profile.xml
=> set text fullname pada forum
